### ISSUE TITLE
DNS interactions show base domain only

### ISSUE THREAD

**Issue by 1lastBr3ath** [hackvertor/taborator#5]
Taborator shows base domain only which is not ideal when there's a lot of pingbacks from the same payload. The following screenshot should serve as a reference where Collborator is showing full domain whereas Taborator's showing base domain only;
![collaborator_vs_taborator](https://user-images.githubusercontent.com/7494618/76193317-d8390800-620b-11ea-8b6c-9e70637c070f.png)

**Comment by justinsteven** [comment]
Big +1 from me

# Reproduction steps

1. Use the traditional "Burp Collaborator client". Generate a collaborator payload (e.g. example1.burpcollaborator.net). Do `dig foobar.example1.burpcollaborator.net`. Note that Burp Collaborator client gets a DNS hit which says "The Collaborator server received a DNS lookup of type A for the domain name foobar.example1.burpcollaborator.net"
2. Use Taborator. Generate a collaborator payload (e.g. example2.burpcollaborator.net). Do `dig foobar.example2.burpcollaborator.net`. Note that Taborator gets a DNS hit which says "The Collaborator server received a DNS lookup of type A for the domain name example2.burpcollaborator.net". **It should say foobar.example2.burpcollaborator.net.**

As an aside, the data produced by "Export" for the DNS hits has an "Interaction ID" (which is just the `example` part of `example.burpcollaborator.net`) but it doesn't have the full hostname. It would be great for the exported data to include the full hostname for DNS hits, including any data prepended to the hostname (See above)

**Comment by justinsteven** [comment]
@1lastBr3ath in case you didn't get a ping, I've filed a PR for this over in PortSwigger's repo

**Comment by 1lastBr3ath** [comment]
@justinsteven Thanks a lot. That looks great to me.
